pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://fabricmc.net'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = 'https://fabricmc.net' }
    }
}

rootProject.name = 'ChatMod'
