name: Build Minecraft Mod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Этот шаг автоматически сгенерирует правильный Gradle Wrapper внутри облака
    - name: Wrapper Setup
      run: gradle wrapper --gradle-version 8.12

    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test

    - name: Upload Mod Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Mod
        path: build/libs/*.jar
